### ISSUE TITLE
Finalize voting method for rebalances

### ISSUE THREAD

**Issue by jackzampolin** [PeggyJV/sommelier#43]
Currently validators must vote every period on allocations. The plan is to use a modular ante-handler to prevent validators from [paying gas on these transactions](https://github.com/PeggyJV/sommelier/issues/38). If there is another desired method here (more sparse voting) we need a specification for it cc @zmanian

**Comment by zmanian** [comment]
Okay here is my suggested algorithm.

1. Voting all zero values is a vote to not rebalance. If 1/3rd +1 of voting power votes to not rebalance, do not rebalance.

2. Otherwise takes all no zero votes, multiple each allocation by voting power + add to the other votes. Divide by "total voting power - minus all zero voting power".

This results in the final rebalance allocations.
